### ISSUE TITLE
Improve code example in README

### ISSUE THREAD

**Issue by pschafhalter** [aqueducthq/aqueduct#21]
It's a bit difficult to parse the example in the README. A few suggestions:
- Using multiple DSLs in the example detracts from showcasing the API. For example, the SQL and the Pandas APIs do similar things, so it would be better to use only 1 for clarity.
- Add comments. I'd include one at the top to explain what specifically the prediction pipeline is doing, and then sprinkle some to explain key parts of the API. For example, I'm curious whether the operator decorator does something to maintain resource allocations, or if the model reaquires the GPU on each invocation. Also, some of the kwargs could be clarified (e.g. update_mode='replace').
- Re-format the example to match the rest of the codebase (uses double quotes whereas the readme example uses single quotes).

**Comment by vsreekanti** [comment]
Thanks, @pschafhalter! #99 addresses most of your feedback. 

The only thing that we didn't do is remove the Pandas DSL -- we currently require users to retrieve data (usually with SQL queries) and manipulate it in Pandas, since most users are comfortable with Pandas. Your feedback is great, and we'll definitely think more about simplifying the API, but it's not something we can support out of the box.
